### ISSUE TITLE
1.2 Observe Pharmacy Shop

### ISSUE THREAD

**Issue by Cassandra-Fu** [hanz105/INF2001-Team-Project-P8-3#12]
Task title ID: 1.2

Task Detail: 
Observe the methods or programs the manager uses to assign workload.
Observe how the staff is informed of assigned workload.
Observe what happens with workload clash.
Observe how availabilities are reported.

Goals:
Have a better understanding of the current workflow and client domain.
Success or completion criteria:
Having observed the workflow of the manager for assigning workload to staff.

Allocated time:
1 Day

Start Date - End Date:
08/09/2023 - 08/09/2023

Owner: Hannah.

Status: Refer to GitHub status.

Priority: Medium.

**Comment by Cassandra-Fu** [comment]
Completed

**Comment by hanz105** [comment]
1. Work Done Detail:
Observed Manager workload assignment.
Ask Manager questions on the current process of assigning workload, what happens when there is clashes, how availabilities are confirmed with staff, and when do reassignments occur.
Ask Branch Staff on how availabilities are discussed and what happens when sudden changes happen.
3. Information gathered and in report.
4. On track for deadline.
6. Start Date and End Date: 08/09/2023 - 08/09/2023

**Comment by AstralAurora** [comment]
Work done, issue closed.
